name: CI

on: push

jobs:
  main:
    name: Build, Test, Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment (pnpm)
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - name: Setup Environment (node)
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm i

      - name: Apply (Format)
        run: pnpm apply:format

      - name: Check (Format)
        run: pnpm check:format

      - name: Commit Formatting Changes (if any)
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'fix: apply formatting'

      - name: Build
        run: pnpm build

      - name: Check (Lint)
        run: pnpm check:lint

      - name: Check (Types)
        run: pnpm check:types

      - name: Test
        run: echo 'TODO, we should eventually have tests'

      - name: Deploy
        run: echo 'TODO, deployment should be managed by our CI'
